#!/bin/bash

source env.sh

cd $STAGE_RUNNER_HOME

cp  $STAGE_RUNNER_HOME/javasrc/java/META-INF/persistence.1.xml $STAGE_RUNNER_HOME/build/web/WEB-INF/classes/META-INF/persistence.xml

ant 

echo "Starting backend demon for stageRunner"

$JAVA_HOME/bin/java -classpath $STAGE_RUNNER_HOME/build/web/WEB-INF/classes:$STAGE_RUNNER_HOME/lib/sapphire/gtlf-libs.jar:$STAGE_RUNNER_HOME/lib/sapphire/gtlf-uploader.jar:$STAGE_RUNNER_HOME/lib/sapphire/gtlfutils-core.jar:$STAGE_RUNNER_HOME/lib/sapphire/jsch-0.1.41.jar:$STAGE_RUNNER_HOME/lib/sapphire/mail.jar:$STAGE_RUNNER_HOME/lib/mysql-connector-java-6.0.2.jar:$STAGE_RUNNER_HOME/lib/org.eclipse.persistence.antlr-2.5.2.jar:$STAGE_RUNNER_HOME/lib/org.eclipse.persistence.asm-2.5.2.jar:$STAGE_RUNNER_HOME/lib/org.eclipse.persistence.core-2.5.2.jar:$STAGE_RUNNER_HOME/lib/org.eclipse.persistence.jpa-2.5.2.jar:$STAGE_RUNNER_HOME/lib/org.eclipse.persistence.jpa.jpql-2.5.2.jar:$SERVER_HOME/modules/endorsed/webservices-api-osgi.jar:$SERVER_HOME/modules/endorsed/jaxb-api-osgi.jar:$SERVER_HOME/modules/endorsed/javax.annotation-api.jar:$SERVER_HOME/modules/javax.management.j2ee-api.jar:$SERVER_HOME/modules/javax.servlet.jsp.jstl-api.jar:$SERVER_HOME/modules/javax.inject.jar:$SERVER_HOME/modules/javax.servlet.jsp.jstl.jar:$SERVER_HOME/modules/webservices-osgi.jar:$SERVER_HOME/modules/javax.enterprise.deploy-api.jar:$SERVER_HOME/modules/javax.transaction-api.jar:$SERVER_HOME/modules/javax.jms-api.jar:$SERVER_HOME/modules/javax.faces.jar:$SERVER_HOME/modules/bean-validator.jar:$SERVER_HOME/modules/javax.interceptor-api.jar:$SERVER_HOME/modules/javax.el.jar:$SERVER_HOME/modules/javax.xml.rpc-api.jar:$SERVER_HOME/modules/javax.servlet.jsp.jar:$SERVER_HOME/modules/jaxb-osgi.jar:$SERVER_HOME/modules/javax.resource-api.jar:$SERVER_HOME/modules/javax.security.jacc-api.jar:$SERVER_HOME/modules/javax.ejb-api.jar:$SERVER_HOME/modules/javax.enterprise.concurrent-api.jar:$SERVER_HOME/modules/javax.json.jar:$SERVER_HOME/modules/javax.ws.rs-api.jar:$SERVER_HOME/modules/javax.enterprise.concurrent.jar:$SERVER_HOME/modules/javax.batch-api.jar:$SERVER_HOME/modules/javax.mail.jar:$SERVER_HOME/modules/javax.servlet-api.jar:$SERVER_HOME/modules/javax.xml.registry-api.jar:$SERVER_HOME/modules/javax.servlet.jsp-api.jar:$SERVER_HOME/modules/javax.persistence.jar:$SERVER_HOME/modules/javax.websocket-api.jar:$SERVER_HOME/modules/weld-osgi-bundle.jar:$SERVER_HOME/modules/javax.security.auth.message-api.jar:$SERVER_HOME/../mq/lib/jaxm-api.jar:$SERVER_HOME/lib/embedded/glassfish-embedded-static-shell.jar com.oracle.stagerun.tool.StageRunDaemon > srdaemon.log &
sleep 10
mv $STAGE_RUNNER_HOME/build/web/WEB-INF/classes/META-INF/persistence.xml $STAGE_RUNNER_HOME/build/web/WEB-INF/classes/META-INF/persistence.1.xml


/usr/local/packages/aime/dte/DTE3/bin/jobReqAgent -toposetid 21103 -toposetMemberID 114195 -p LINUX.X64 -r 12.2.1.3.0  -s /ade_autofs/gd59_fmw/ASCORE_12.2.1.3.0_LINUX.X64.rdd/LATEST/ascore/shiphome/fmw_12.2.1.3.0_otd_linux64.bin  -preExecuted=OTD_Setup.DOWNLOAD_TEST1,OTD_MT.DOWNLOAD_TEST1,DOWNLOAD_TEST1 -preExportedFile=$HOME/download_export.txt,$HOME/download_export.txt,$HOME/download_export.txt ENV:MY_JRF_SHIPHOME_LOCATION=/ade_autofs/gd17_fmw/ASKERNEL_12.2.1.3.0_GENERIC.rdd/LATEST/askernel/shiphome/fmw_12.2.1.3.0_infrastructure_generic.jar -l OTDQA_MAIN_GENERIC_170214.0800 -intgflag 4 -txn_name=mseelam_ha_active_active_bug_fix_trans1 -txn_view_name=mseelam_otd_slc07phi -txn_hostname=slc07phi.us.oracle.com